name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup nspire Tools
      uses: alexcoder04/setup-nspire-tools@v1

    - name: Build project
      run: make build

    - name: Save tns
      uses: actions/upload-artifact@v3
      with:
        name: tns
        path: |
          calcdist.tns
